language: python
python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=prettytypo nosetest

after_success:
  - coveralls
